# Podfile
# The target 'Runner' is defined in this file, and is a Pods project that depends on the Flutter framework.

platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
env['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join(
    File.dirname(__FILE__), 'Flutter', 'Flutter-Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\s*=\s*(.*)$/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Flutter-Generated.xcconfig, then run flutter pub get"
end

def flutter_version
  generated_version_path = File.expand_path(File.join(
    File.dirname(__FILE__), 'Flutter', 'Flutter-Version.xcconfig'), __FILE__)
  unless File.exist?(generated_version_path)
    raise "#{generated_version_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_version_path) do |line|
    matches = line.match(/FLUTTER_VERSION\s*=\s*(.*)$/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_VERSION not found in #{generated_version_path}. Try deleting Flutter-Version.xcconfig, then run flutter pub get"
end

def flutter_root_plugins
  generated_plugins_path = File.expand_path(File.join(
    File.dirname(__FILE__), 'Flutter', 'Flutter-Plugins.xcconfig'), __FILE__)
  unless File.exist?(generated_plugins_path)
    raise "#{generated_plugins_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_plugins_path) do |line|
    matches = line.match(/FLUTTER_PLUGIN_SEARCH_PATHS\s*=\s*(.*)$/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_PLUGIN_SEARCH_PATHS not found in #{generated_plugins_path}. Try deleting Flutter-Plugins.xcconfig, then run flutter pub get"
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'PERMISSION_LOCATION=1',
      ]
    end
  end
end
